server:
  port: 8082
spring:
  rabbitmq:
    host: localhost
    port: 5672
    usrname: guest
    password: guest
    request:
      exchange:
        producer: ex.producer.aula-spring
      routing-key:
        producer: rk.producer.aula-spring
      dead-letter:
        producer: dl.producer.aula-spring
      parking-lot:
        producer: pl.producer.aula-spring